version: "3"
services:
  app:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password123
    volumes:
      - db_volume:/var/lib/postgres/data

volumes:
  db_volume:
